# Generated by Django 4.0 on 2022-03-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_liveclass_student_liveclass_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('TestName', models.CharField(max_length=250)),
                ('StartTime', models.DateTimeField(null=True)),
                ('EndTime', models.DateTimeField(null=True)),
                ('Testlink', models.CharField(max_length=250)),
                ('student', models.ManyToManyField(related_name='student_ClassTest', to='classroom.Student')),
                ('teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_ClassTest', to='classroom.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
