# Generated by Django 4.0 on 2022-03-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_classassignment_assignment_classmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='assignment',
            field=models.FileField(upload_to='assignments'),
        ),
        migrations.AlterField(
            model_name='classmaterial',
            name='material',
            field=models.FileField(upload_to='materials'),
        ),
    ]
