# Generated by Django 4.0 on 2022-03-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_liveclass_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='Classlink',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
